"""rename description

Revision ID: a68611a90182
Revises: aa961af7712b
Create Date: 2024-05-13 18:40:21.604531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68611a90182'
down_revision: Union[str, None] = 'aa961af7712b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'discreption', nullable=False, new_column_name='description')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'description', nullable=False, new_column_name='discreption')
    # ### end Alembic commands ###
